/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/AdminBlock.glb -o ./src/components/AdminBlock.jsx -r 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/AdminBlock.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.005']} position={[0.896, 0.123, 0.044]} scale={[0.931, 0.17, 0.235]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.008']} position={[1.054, 0.215, 0.11]} scale={[0.124, 0.262, 0.301]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.006']} position={[0.929, 0.275, 0.171]} scale={[0.008, 0.322, 0.363]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.004']} position={[0.929, 0.093, 0.438]} rotation={[0, 0, -Math.PI / 2]} scale={[0.008, 0.514, 0.363]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Material} position={[0.763, 0.201, 0.11]} scale={[0.156, 0.249, 0.301]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.009']} position={[0.929, -0.04, 0.402]} rotation={[0, 0, -Math.PI / 2]} scale={[0.008, 0.478, 0.135]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.002']} position={[0.581, 0.021, 0.357]} scale={[0.13, 0.062, 0.163]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.001']} position={[1.331, 0.021, 0.357]} scale={[0.076, 0.062, 0.163]} />
    </group>
  )
}

useGLTF.preload('/models/AdminBlock.glb')
