/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/astro.glb -o ./src/components/astro.jsx 
Author: nitwit.friends (https://sketchfab.com/nitwit.friends)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hatchxr-astronaut-81338170583f4e4cab5e1731a6f9765a
Title: HatchXR Astronaut
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useEffect } from 'react'

export function Model({ animation = "float", ...props }) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/astro.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  console.log(actions);
  console.log(animations);

    useEffect(() => {
    if (!actions || !actions[animation]) return;

    actions[animation].reset().fadeIn(0.25).play();

    return () => {
      actions[animation]?.fadeOut(0.25);
    };
  }, [animation, actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={69.718}>
          <group name="fbx_mergefbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" />
                  <group name="CINEMA_4D_Editor" position={[5.713, 5.07, 4.713]} rotation={[-Math.PI, 0.752, 2.865]}>
                    <group name="Object_79" />
                  </group>
                  <group name="Astronaut_mesh" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Astronaut_matmat} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Matmat} skeleton={nodes.Object_8.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.material} skeleton={nodes.Object_9.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/astro.glb')
