/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/building.glb -o ./src/components/building.jsx 
*/

import React from 'react'
import { useGLTF, Clone } from '@react-three/drei'
import { DissolveMaterial } from './DissolveEffect'

export function Model(props) {
  const { scene } = useGLTF('/models/AdminBlock.glb')
  return (
    <group {...props} dispose={null}>
    <Clone object={scene} />
    </group>
  )
}

useGLTF.preload('/models/AdminBlock.glb')
