/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/lib.glb -o ./src/components/lib.jsx 

*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { DissolveMaterial } from './DissolveEffect'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/lib.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model.geometry} material={materials.model} />
      
       <DissolveMaterial baseMaterial={materials.model} visible color="#0082b2"/>
    </group>
  )
}

useGLTF.preload('/lib.glb')
