/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/library.glb -o ./src/components/library.jsx -r 
*/

import React from 'react'
import { useGLTF, Clone } from '@react-three/drei'

export function Model(props) {
  const { scene } = useGLTF('/models/librarybuilding.glb')
  return (
    <group {...props}>
      <Clone object={scene} />
    </group>
  )
}

useGLTF.preload('/models/librarybuilding.glb')
