/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/library.glb -o ./src/components/library.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/library.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model.geometry} material={materials.model} />
    </group>
  )
}

useGLTF.preload('/models/library.glb')
