/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/purple_planet.glb -o ./src/components/purple_planet.jsx 
Author: Yo.Ri (https://sketchfab.com/grox777)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/purple-planet-264eb22207184fc99a5e3b1279a763b8
Title: Purple Planet
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect } from 'react'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/purple_planet.glb')
  const { actions } = useAnimations(animations, group)
    useEffect(() => {
      if (!actions) return
  
      Object.values(actions).forEach((action) => {
        action.reset().play()
      })
  
      return () => {
        Object.values(actions).forEach((action) => action.stop())
      }
    }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Planet" rotation={[0, 0, Math.PI / 2]}>
              <group name="Clouds_0" rotation={[0, 0, -Math.PI / 2]} scale={1.013}>
                <mesh name="Clouds_0_0" geometry={nodes.Clouds_0_0.geometry} material={materials.Clouds_0} />
              </group>
              <mesh name="Planet_0" geometry={nodes.Planet_0.geometry} material={materials.PurplePlanet} />
            </group>
            <group name="Clouds_1" scale={1.019}>
              <mesh name="Clouds_1_0" geometry={nodes.Clouds_1_0.geometry} material={materials.Clouds_1} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/purple_planet.glb')
