/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/robot.glb -o ./src/components/robot.jsx 
Author: (Andy An)norbyscook (https://sketchfab.com/norbyscook)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-maintenance-robot-a612ed4feea14fc390beeb3a47943054
Title: space maintenance robot
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { DissolveMaterial } from './DissolveEffect'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/robot.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['defaultMat.001']} rotation={[-Math.PI / 2, 0, 0]} >
        {/* <DissolveMaterial baseMaterial={materials["defaultMat.001"]} visible color="#0082b2" /> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('models/robot.glb')
