/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/sign.glb -o ./src/components/sign.jsx -r 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/sign.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model005.geometry} material={materials.model} />
      <mesh geometry={nodes.model005_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.model005_2.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.model005_3.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.model005_4.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.model005_5.geometry} material={materials['model.003']} />
    </group>
  )
}

useGLTF.preload('/models/sign.glb')
